---
- name: Check connectivity
  ping:

- name: Disable Swap on all nodes
  shell: swapoff -a
  tags:
    - os_config

- name: Check if fstab exists
  stat:
    path: /etc/fstab
  register: fstab_exists
  tags:
    - os_config

- name: Comment Swap entries in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '(.*swap*)'
    replace: '#\1'
  when: fstab_exists.stat.exists == True
  tags:
    - os_config

- name: Copy network config files
  ansible.builtin.copy:
    src: "../files/{{ item.name }}"
    dest: "{{ item.destination }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - {name: 'modules-load.d_k8s.conf', destination: '/etc/modules-load.d/k8s.conf'}
    - {name: 'sysctl.d_k8s.conf', destination: '/etc/sysctl.d/k8s.conf'}
  tags:
    - os_config

- name: Set firewall rules
  shell: |
    ufw allow 6443/tcp
    ufw allow 2379:2380/tcp
    ufw allow 10250:10259/tcp
    ufw allow 30000:32767/tcp
    ufw reload
  tags:
    - os_config

- name: Refresh kernel settings
  shell: sysctl --system
  tags:
    - os_config

- name: Install required OS packages
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present
  tags:
    - os_config

- name: Add Docker apt-key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/docker-archive-keyring.gpg
  tags:
    - repo

- name: Add Docker Repository
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  notify: Apt cache
  tags:
    - repo

- name: Add Kubernetes apt-key
  shell: curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
  args:
    creates: /usr/share/keyrings/kubernetes-archive-keyring.gpg
  tags:
    - repo

- name: Add Kubernetes Repository
  shell: echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
  notify: Apt cache
  tags:
    - repo

- name: Flush handlers    # Execute handlers immidiatelly
  meta: flush_handlers

- name: Install Docker packages
  ansible.builtin.package:
    name: "{{ docker_packages }}"
    state: present
  tags:
    - os_config

- name: Install Kubernetes packages
  ansible.builtin.package:
    name: "{{ kubernetes_packages }}"
    state: present
  tags:
    - os_config

- name: Prevent kubernetes from being upgraded
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items: 
    - "{{ kubernetes_packages }}"
  tags:
    - os_config

- name: Copy docker config files
  ansible.builtin.copy:
    src: "../files/{{ item.name }}"
    dest: "{{ item.destination }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - {name: 'docker_cgroup', destination: '/etc/docker/daemon.json'}
  tags:
    - os_config

- name: Restart docker
  service:
    name: docker
    state: restarted
    enabled: true
  tags:
    - os_config

- name: Reboot
  reboot:
    reboot_timeout: 180
  tags:
    - reboot
