Vagrant.configure("2") do |config|

	# Specify the base box
	  config.vm.box = "centos/7"
    config.vm.hostname = "centos7"
		config.vm.define "centos7"

    # VM specific configs
    config.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
				vb.name = "centos7"
    end

	# Network configuration
	#config.vm.network :forwarded_port, guest: 80, host: 80, auto_correct: true
    config.vm.network "private_network", ip: "192.168.60.11"

    # Setup synced folder
    config.vm.synced_folder "../common_scripts", "/tmp"

    # Shell provisioning
    #config.vm.provision "shell" , inline <<--SHELL
    #	yum update
    #   yum install -y httpd
    #SHELL

    config.vm.provision "shell", path: "../common_scripts/setup.sh"
end
