Vagrant.configure("2") do |config|

    # Specify the base box
    config.vm.box = "centos/7"
    config.vm.hostname = "host1"
    config.vm.define "host1"

    # VM specific configs
    config.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
				vb.name = "host1"
    end

	# Network configuration
	  config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "private_network", ip: "192.168.60.11"

    # Setup synced folder
    config.vm.synced_folder "../common_scripts", "/tmp"

    # Shell provisioning
    #config.vm.provision "shell" , inline <<--SHELL
    #	yum update
    #   yum install -y httpd
    #SHELL

    config.vm.provision "shell", path: "../common_scripts/setup.sh"
    config.vm.provision "ansible" do |ansible|
      ansible.inventory_path = "../common_scripts/ansible_playbooks/inventory"
      ansible.playbook = "../common_scripts/ansible_playbooks/install_os_tools.yaml"
    end
   config.vm.provision "ansible" do |ansible|
      ansible.playbook = "../common_scripts/ansible_playbooks/install_nginx.yaml"
   end
end
