trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller
  displayName: Terraform install
  inputs:
    terraformVersion: latest

- task: TerraformTaskV2@2
  name: 'terraform_init'
  displayName: 'Terraform init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'WSBAzureSP'

#- task: TerraformTaskV2@2
#  name: 'terraform_validate'
#  displayName: 'Terraform validate'
#  inputs:
#    provider: 'azurerm'
#    command: 'validate'

#- task: TerraformTaskV2@2
#  name: 'terraform_plan'
#  displayName: 'Terraform plan'
#  inputs:
#    provider: 'azurerm'
#    command: 'plan'

#- task: TerraformTaskV2@2
#  name: 'terraform_apply'
#  displayName: 'Terraform apply'
#  inputs:
#    provider: 'azurerm'
#    command: 'apply'
