trigger:
  batch: false
  branches:
    include:
    - master
  paths:
    include:
    - /terraform/azure-infra/example1/

pool:
  vmImage: ubuntu-latest

stages :
  - stage: validate
    jobs:
    - job: validate
      continueOnError: false
      steps:
      - task: TerraformInstaller@0
        displayName: 'install'
        inputs:
          terraformVersion: 'latest'
      - task: TerraformTaskV1@0
        displayName: 'init'
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'WSBAzureSP'
      - task: TerraformTaskV1@0
        displayName: 'validate'
        inputs:
          provider: 'azurerm'
          command: 'validate'
          backendServiceArm: 'WSBAzureSP'
          

#- task: TerraformTaskV2@2
#  name: 'terraform_validate'
#  displayName: 'Terraform validate'
#  inputs:
#    provider: 'azurerm'
#    command: 'validate'

#- task: TerraformTaskV2@2
#  name: 'terraform_plan'
#  displayName: 'Terraform plan'
#  inputs:
#    provider: 'azurerm'
#    command: 'plan'

#- task: TerraformTaskV2@2
#  name: 'terraform_apply'
#  displayName: 'Terraform apply'
#  inputs:
#    provider: 'azurerm'
#    command: 'apply'
