parameters:
- name: image
  displayName: Pool Image
  type: string
  default: ubuntu-latest
  values:
  - ubuntu-latest

trigger:
  batch: false
  branches:
    include:
    - master
  paths:
    include:
    - /terraform/azure-infra/example1/

stages :
  - stage: Validation
    jobs:
    - job: validate
      continueOnError: false
      pool:
        vmImage: '${{ parameters.image }}'
      steps:
      - task: TerraformInstaller@0
        displayName: 'install'
        inputs:
          terraformVersion: '0.12.3'
      - task: TerraformTaskV1@0
        displayName: 'init'
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendAzureRmStorageAccountName: 'storagefortfcode'
          backendAzureRmContainerName: 'terraform'
          backendServiceArm: 'WSBAzureSP'
          backendAzureRmResourceGroupName: 'Terraform'
          backendAzureRmKey: 'terraform.tfstate'
      - task: TerraformTaskV1@0
        displayName: 'validate'
        inputs:
          provider: 'azurerm'
          command: 'validate'
          backendServiceArm: 'WSBAzureSP'
          

#- task: TerraformTaskV2@2
#  name: 'terraform_validate'
#  displayName: 'Terraform validate'
#  inputs:
#    provider: 'azurerm'
#    command: 'validate'

#- task: TerraformTaskV2@2
#  name: 'terraform_plan'
#  displayName: 'Terraform plan'
#  inputs:
#    provider: 'azurerm'
#    command: 'plan'

#- task: TerraformTaskV2@2
#  name: 'terraform_apply'
#  displayName: 'Terraform apply'
#  inputs:
#    provider: 'azurerm'
#    command: 'apply'
