name: $(Build.Repository.Name)-$(Build.SourceBranchName)

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md
    include:
      - envs/dev/*
      - pipelines/pipeline-dev.yml

pool: vmss-usec-dev-weu-vmss-001

parameters:
  - name: action
    displayName: Action
    type: string
    default: 'Plan'
    values:
    - Plan
    - Apply
    - Destroy

variables:
  - name: ServiceConnection
    value: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    readonly: true
  - name: TargetSubscriptionID
    value: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    readonly: true
  - name: env
    value: dev
    readonly: true
  
stages:
  - stage: Terraform_scan
    dependsOn: []
    jobs:
      - job: TFsec
        steps:
          - template: security/scan.yml
            parameters:
              ServiceConnection: ${{ variables.ServiceConnection }}
  - stage: Install_Terragrunt
    dependsOn: [Terraform_scan]
    jobs:
      - job: Terragrunt_Installation
        steps:
          - template: terragrunt_steps/install.yml
  - stage: Plan
    condition: eq('${{ parameters.Action }}', 'Plan')
    dependsOn: [Install_Terragrunt]
    jobs:
      - job: Plan
        timeoutInMinutes: 20
        steps:
          - template: terragrunt_steps/init.yml
            parameters:
              env: ${{ variables.env }}
              ServiceConnection: ${{ variables.ServiceConnection }}
              TargetSubscriptionID: ${{ variables.TargetSubscriptionID }}
          - template: terragrunt_steps/plan.yml
            parameters:
              env: ${{ variables.env }}
              ServiceConnection: ${{ variables.ServiceConnection }}
              TargetSubscriptionID: ${{ variables.TargetSubscriptionID }}
  - stage: Apply
    condition: eq('${{ parameters.Action }}', 'Apply')
    dependsOn: [Install_Terragrunt]
    jobs:
      - job: Apply
        steps:
          - template: terragrunt_steps/init.yml
            parameters:
              env: ${{ variables.env }}
              ServiceConnection: ${{ variables.ServiceConnection }}
              TargetSubscriptionID: ${{ variables.TargetSubscriptionID }}
          - template: terragrunt_steps/plan.yml
            parameters:
              env: ${{ variables.env }}
              ServiceConnection: ${{ variables.ServiceConnection }}
              TargetSubscriptionID: ${{ variables.TargetSubscriptionID }}
          - template: terragrunt_steps/apply.yml
            parameters:
              env: ${{ variables.env }}
              ServiceConnection: ${{ variables.ServiceConnection }}
              TargetSubscriptionID: ${{ variables.TargetSubscriptionID }}
