Vagrant.configure("2") do |config|
   (1..2).each do |i|

      #Define node variables
      config.vm.define "node#{i}" do |node|
      # box configuration
      node.vm.box = "centos/7"
      # Setting the host name of the virtual machine
      node.vm.hostname = "node#{i}"
      # Setting up IP of Virtual Machine
      node.vm.network "private_network", ip: "192.168.60.#{10+i}"
      # Setting up shared directories between hosts and virtual machines
      node.vm.synced_folder ".", "/tmp"
			#provision files
			node.vm.provision "shell", path: "scripts/setup.sh"
      # VirtaulBox related configuration
      node.vm.provider "virtualbox" do |v|
          # Set the name of the virtual machine
          v.name = "node#{i}"
          # Setting the memory size of the virtual machine
          v.memory = 2048
          # Setting CPU Number of Virtual Machines
          v.cpus = 1
      end
  end
end
end
