Vagrant.configure("2") do |config|
   (1..2).each do |i|

    #Define node variables
    config.vm.define "host#{i}" do |host|
    # box configuration
    host.vm.box = "centos/7"
    # Setting the host name of the virtual machine
    host.vm.hostname = "host#{i}"
    # Setting up IP of Virtual Machine
    host.vm.network "private_network", ip: "192.168.60.#{10+i}"
    # Setting up shared directories between hosts and virtual machines
    host.vm.synced_folder "scripts", "/tmp"
		#provisioning
		host.vm.provision "shell", path: "scripts/setup.sh"

    # VirtaulBox related configuration
        host.vm.provider "virtualbox" do |v|
        # Set the name of the virtual machine
        v.name = "host#{i}"
        # Setting the memory size of the virtual machine
        v.memory = 2048
        # Setting CPU Number of Virtual Machines
        v.cpus = 1
    end
  end
end
end
