---
- name: Base config
  hosts: all
  gather_facts: true
  become_user: root
  become_method: sudo
  become: true

  vars:
    packages:
      - python3
      - python3-pip
      - net-tools
      - nmap
      - telnet
      - git
    python_pip_packages:
      - docker-py


  pre_tasks:
    - name: check connectivity
      ping:

  tasks:
    - name: Update /etc/hosts
      blockinfile:
        path: /etc/hosts
        block: |
          {% for host in groups['all'] %}
          {{ hostvars[host].ansible_default_ipv4.address }} {{ host }}
          {% endfor %}
      tags:
        - hosts

    - name: create admin group "admins"
      group:
        name: admins
        state: present
      tags:
        - user_mgmnt

    - name: Create users
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: present
        shell: "{{ item.shell }}"
        groups: "{{ item.groups }}"
        create_home: true
      no_log: true
      loop:
        - {name: 'przemek', groups: 'admins', shell: '/bin/bash'}
      tags:
        - user_mgmnt

    - name: Update authorized keys
      authorized_key:
        user: "{{ item }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      with_items:
        - przemek
      tags:
        - user_mgmnt

    - name: Allow sudo for admins group
      copy:
        content: "%admins ALL=(ALL) NOPASSWD:ALL"
        dest: /etc/sudoers.d/admins
        mode: 0600
      tags:
        - user_mgmnt

    - name: Update system
      apt:
        name: "*"
        state: latest
        update_cache: true
        autoremove: true
      tags:
        - os_config

    - name: Install OS packages
      apt:
        name: "{{ packages }}"
        state: present
      tags:
        - os_config

    - name: Install python-pip packages
      pip:
        name: "{{ python_pip_packages }}"

    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname }}"
      tags:
        - os_config

    - name: Set timezone to Europe/Warsaw
      shell: timedatectl set-timezone "Europe/Warsaw"

    - name: Reboot
      reboot:
        reboot_timeout: 180
      tags:
        - reboot
