---
- name: Kubernetes preflight
  hosts: all
  gather_facts: true
  become_user: root
  become_method: sudo
  become: true

  pre_tasks:
    - name: Check connectivity
      ping:
    - name: Fail when OS not Ubuntu
      fail:
        msg: OS version is not Ubuntu
      when: '"Ubuntu" not in ansible_distribution'

  tasks:
    - import_role:
        name: kubernetes_preflight
        tasks_from: main.yml

- name: Kubernetes master
  hosts: master
  gather_facts: true

  pre_tasks:
    - name: Check connectivity
      ping:

  tasks:
    - import_role:
        name: kubernetes_master
        tasks_from: main.yml