---
- name: Maintenance
  hosts: all
  gather_facts: true
  user: przemek
  become: true

  pre_tasks:
  - name: check connectivity
    ping:

  tasks:
  - name: Update cache
    apt:
      update_cache: true

  - name: Upgrade all packages on servers
    apt:
      name: "*"
      state: latest
