---
- name: Pihole playbook
  hosts: pihole.oci
  gather_facts: true
  become_user: root
  become_method: sudo
  become: true
  collections:
  - community.docker

  vars_files:
  -  vault.yml

  pre_tasks:
  - name: Check connectivity
    ping:
  
  tasks:
  - name: Create local mount paths
    file:
      state: directory
      path: "/datadisk/pihole/{{ item }}"
      owner: root
      group: root
      mode: '0777'
    with_items:
    - app
    - dnsmasq
  
  - name: Dsable DNS service
    service:
      name: systemd-resolved.service
      state: stopped
      enabled: false

  - name: Insert custom DNS
    lineinfile:
      path: /etc/resolv.conf
      line: nameserver 1.1.1.1

  - name: Create Docker network
    community.docker.docker_network:
      name: pihole_network
      ipam_config:
        - subnet: 10.0.0.0/24

  - name: Run Pihole docker container
    docker_container:
      name: pihole
      image: pihole/pihole
      state: started
      env:
        TZ: "Europe/Warsaw"
        SERVER_IP: "{{ ansible_host }}"
        WEBPASSWORD: "{{ pihole_webpass }}"
      volumes:
        - /datadisk/pihole/app:/etc/pihole/
        - /datadisk/pihole/dnsmasq:/etc/dnsmasq.d/
      ports:
        - 8090:80/tcp
        - 53:53/tcp
        - 53:53/udp
        - 67:67/udp
      networks:
        - name: pihole_network
          ipv4_address: "10.0.0.2"
      restart_policy: unless-stopped