parameters:
- name: image
  displayName: Pool Image
  type: string
  default: ubuntu-latest
  values:
  - ubuntu-latest

trigger:
  batch: false
  branches:
    include:
    - azure_example1_terraform_devops_pipeline
  paths:
    include:
    - terraform/azure-infra/example1/

stages :
  - stage: Installation
    jobs:
    - job: Check
      continueOnError: false
      pool:
        vmImage: '${{ parameters.image }}'
      steps:
      - task: TerraformInstaller@0
        inputs:
          terraformVersion: '0.12.3'
      - task: TerraformTaskV2@2
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'WSBAzureSP'
          backendAzureRmResourceGroupName: 'Terraform'
          backendAzureRmStorageAccountName: 'storagefortfcode'
          backendAzureRmContainerName: 'terraform'
          backendAzureRmKey: 'terraform.tfstate'

      - task: TerraformTaskV2@2
        inputs:
          provider: 'azurerm'
          command: 'validate'

      - task: TerraformTaskV2@2
        inputs:
          provider: 'azurerm'
          command: 'plan'
          environmentServiceNameAzureRM: 'WSBAzureSP'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
