parameters:
- name: image
  displayName: Pool Image
  type: string
  default: ubuntu-latest
  values:
  - ubuntu-latest

trigger:
  batch: false
  branches:
    include:
    - azure_example1_terraform_devops_pipeline
  paths:
    include:
    - terraform/azure-infra/example1/

stages :
  - stage: Installation
    jobs:
    - job: Install_Terraform
      continueOnError: false
      pool:
        vmImage: '${{ parameters.image }}'
      steps:
      - script: |
          sudo apt upgrade -y
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt install -y terraform
          terraform providers
          terraform --version
        displayName: Install Terraform
    - job: Init_Provider
      steps:
      - task: TerraformTaskV2@2
        displayName: 'init'
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendAzureRmStorageAccountName: 'storagefortfcode'
          backendAzureRmContainerName: 'terraform'
          backendServiceArm: 'WSBAzureSP'
          backendAzureRmResourceGroupName: 'Terraform'
          backendAzureRmKey: 'terraform.tfstate'
  - stage: Validation
    jobs:
    - job: Validate_code
      steps:
      - task: TerraformTaskV2@2
        displayName: 'validate'
        inputs:
          provider: 'azurerm'
          command: 'validate'
          backendServiceArm: 'WSBAzureSP'
  - stage: Deployment
    jobs:
    - job: Terraform_plan
      steps:
        - task: TerraformTaskV1@0
          displayName: 'plan'
          inputs:
            provider: 'azurerm'
            command: 'plan'
            environmentServiceNameAzureRM: 'WSBAzureSP'
            configurationDirectory: '$(System.DefaultWorkingDirectory)\terraform\terra'
#        - task: TerraformTaskV1@0
#          displayName: 'apply'
#          inputs:
#            provider: 'azurerm'
#            command: 'apply'
#            environmentServiceNameAzureRM: 'tamopstf'
          
